DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS comments;

CREATE TABLE notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL
);

CREATE TABLE comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    comment VARCHAR(255),
    author VARCHAR,
    note_id INT REFERENCES notes,
    created TIMESTAMP
)
