"""add  content  preview  column

Revision ID: c84d1c9eb9a7
Revises: f646eab1ac68
Create Date: 2022-06-02 14:14:39.540192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84d1c9eb9a7'
down_revision = 'f646eab1ac68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content_preview', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'content_preview')
    # ### end Alembic commands ###
