"""empty message

Revision ID: e24161bfff7b
Revises: 8f2e695522bb
Create Date: 2022-05-28 22:46:21.231536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24161bfff7b'
down_revision = '8f2e695522bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_content', table_name='post')
    op.drop_index('ix_post_created', table_name='post')
    op.drop_index('ix_post_title', table_name='post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_title', 'post', ['title'], unique=False)
    op.create_index('ix_post_created', 'post', ['created'], unique=False)
    op.create_index('ix_post_content', 'post', ['content'], unique=False)
    # ### end Alembic commands ###
