"""add  thumbnail_url  column

Revision ID: e386160379d9
Revises: c84d1c9eb9a7
Create Date: 2022-06-02 15:48:55.032108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e386160379d9'
down_revision = 'c84d1c9eb9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'thumbnail_url')
    # ### end Alembic commands ###
